"""Guards the Windows executable metadata against drifting from APP_VERSION.

version_info.txt is embedded into the .exe by PyInstaller. build-windows.ps1
regenerates it for release builds, but the committed copy is what a manual
``pyinstaller chrisnov-media-toolkit.spec`` run picks up — it was left at
0.2.0-beta.2 while APP_VERSION had already moved to 0.2.0-beta.3.
"""

import re
from pathlib import Path

from app.constants import APP_VERSION

VERSION_INFO = Path(__file__).resolve().parent.parent / "version_info.txt"


def _text() -> str:
    # utf-8-sig: tolerate a BOM if the file was regenerated by a Windows
    # PowerShell 5.1 host (Set-Content -Encoding UTF8 writes one).
    return VERSION_INFO.read_text(encoding="utf-8-sig")


def _string_struct(field: str) -> str:
    match = re.search(rf"StringStruct\('{field}',\s*'([^']*)'", _text())
    assert match, f"{field} missing from version_info.txt"
    return match.group(1)


def test_app_version_is_ascii():
    """APP_VERSION feeds the file version strings; keep it ASCII-safe."""
    assert APP_VERSION.isascii()


def test_committed_file_carries_app_version():
    for field in ("FileVersion", "ProductVersion"):
        assert _string_struct(field) == APP_VERSION, f"{field} drifted"


def test_numeric_version_tuple_matches_app_version():
    match = re.search(r"filevers=\(([^)]*)\)", _text())
    assert match, "filevers missing from version_info.txt"
    numbers = tuple(int(part) for part in match.group(1).replace(" ", "").split(","))
    expected = tuple(int(part) for part in APP_VERSION.split("-")[0].split(".")) + (0,)
    assert numbers == expected


def test_file_is_pure_ascii():
    """PyInstaller parses this file as Python source; non-ASCII bytes depend on
    the build host's encoding assumptions, so we keep it ASCII-only."""
    raw = VERSION_INFO.read_bytes()
    raw.decode("ascii")
